version: '3'
services:
  web:
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=0
      - INSTAPY_WORKSPACE=/code/InstaPy
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./:/code
