version: "3"
services:
  web:
    image: instapy/instapy:latest
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=0
      - INSTAPY_WORKSPACE=/code/InstaPy
    volumes:
      - ./:/code
      ../login_util.py:/usr/local/lib/python3.7/site-packages/instapy/login_util.py
